-- Add new styling fields to TemplateField table
-- These fields enable advanced styling options in the template editor

-- Rotation and layering
ALTER TABLE "TemplateField" ADD COLUMN IF NOT EXISTS "rotation" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "TemplateField" ADD COLUMN IF NOT EXISTS "zIndex" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "TemplateField" ADD COLUMN IF NOT EXISTS "blendMode" TEXT NOT NULL DEFAULT 'normal';

-- Shadow properties
ALTER TABLE "TemplateField" ADD COLUMN IF NOT EXISTS "shadowEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "TemplateField" ADD COLUMN IF NOT EXISTS "shadowColor" TEXT NOT NULL DEFAULT '#000000';
ALTER TABLE "TemplateField" ADD COLUMN IF NOT EXISTS "shadowBlur" DOUBLE PRECISION NOT NULL DEFAULT 4;
ALTER TABLE "TemplateField" ADD COLUMN IF NOT EXISTS "shadowOffsetX" DOUBLE PRECISION NOT NULL DEFAULT 2;
ALTER TABLE "TemplateField" ADD COLUMN IF NOT EXISTS "shadowOffsetY" DOUBLE PRECISION NOT NULL DEFAULT 2;

-- Text styling
ALTER TABLE "TemplateField" ADD COLUMN IF NOT EXISTS "letterSpacing" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "TemplateField" ADD COLUMN IF NOT EXISTS "lineHeight" DOUBLE PRECISION NOT NULL DEFAULT 1.2;
ALTER TABLE "TemplateField" ADD COLUMN IF NOT EXISTS "textTransform" TEXT NOT NULL DEFAULT 'none';

-- Shape properties (for image fields)
ALTER TABLE "TemplateField" ADD COLUMN IF NOT EXISTS "borderRadius" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "TemplateField" ADD COLUMN IF NOT EXISTS "borderWidth" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "TemplateField" ADD COLUMN IF NOT EXISTS "borderColor" TEXT NOT NULL DEFAULT '#000000';

-- Effects
ALTER TABLE "TemplateField" ADD COLUMN IF NOT EXISTS "effectType" TEXT;
ALTER TABLE "TemplateField" ADD COLUMN IF NOT EXISTS "effectIntensity" DOUBLE PRECISION NOT NULL DEFAULT 50;

